# Generated by Django 5.2 on 2026-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('transport_type', models.CharField(blank=True, choices=[('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('bike', 'Bike'), ('walk', 'Walk')], max_length=20, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('electricity_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('food_type', models.CharField(blank=True, choices=[('meat', 'Meat'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], max_length=20, null=True)),
                ('carbon_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('breakdown_transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('breakdown_electricity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('breakdown_food', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
